services:
  postgresql:
    image: "postgres:14"
    container_name: "postgresql"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - 'postgresql-data:/var/lib/postgresql/data'
volumes:
  postgresql-data:
