default: &default
  adapter: postgresql
  encoding: unicode
  username: tc
  password:
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: whowashere

test:
  <<: *default
  database: whowashere_test

production:
  <<: *default
  database: heroku_does_this
